In [23]:

# coding: utf-8

# In[4]:


import numpy as np
from PIL import Image, ImageOps
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix

from keras.models import Sequential
from keras.layers import InputLayer
from keras.layers.convolutional import Conv2D
from keras.layers.pooling import MaxPool2D
from keras.optimizers import Adam

from keras.layers.core import Dense, Activation, Dropout, Flatten
from keras.utils import plot_model
from keras.callbacks import TensorBoard

#from keras.datasets import cifar10
from keras.utils import np_utils

from keras.preprocessing.text import Tokenizer

from keras.models import load_model

import matplotlib

import os
import glob


# In[4]:


from keras.models import Sequential


# In[5]:


files = glob.glob('./converted/*/*.jpeg')

images = []
targets = []

for f in files:
    # file data to array
    arr = np.array(Image.open(f))#.flatten()
    images.append(arr)
    
    target = os.path.basename(os.path.dirname(f))
    targets.append(target)

data_train, data_test, label_train, label_test = train_test_split(images, targets, test_size=0.3)


# In[33]:


In [24]:
# print(data_train)

In [25]:
pwd

'C:\\Users\\p000524252\\jupyter\\Challenge4'

In [26]:
data_train = np.array(data_train)
data_test = np.array(data_test)
#label_train = np.array(label_train)

label = list(set(label_train))
label
label_train2 = []

for i in label_train:
    label_train2.append(label.index(i))

label_train3 = np_utils.to_categorical(label_train2 , 12)

In [27]:
# In[34]:
data_train = data_train.astype('float32')/255
data_test = data_test.astype('float32')/255

classes = 12

# data_train = np_utils.to_categorical(data_train, classes)
# data_test = np_utils.to_categorical(data_test, classes)


In [28]:
print(data_train)

[[[[1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   ...
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]]

  [[1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   ...
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]]

  [[1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   ...
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]]

  ...

  [[1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   ...
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]]

  [[1.         1.         1.        ]
   [1. 

In [29]:
# In[45]:




model = Sequential()

model.add(Conv2D(32,4,input_shape=(128,128,3)))
model.add(Activation('relu'))

model.add(MaxPool2D(pool_size=(2,2)))
model.add(Activation('relu'))

model.add(Conv2D(128,3))
model.add(Activation('relu'))

model.add(MaxPool2D(pool_size=(2,2)))
model.add(Activation('relu'))

model.add(Flatten())
model.add(Dense(classes))
model.add(Activation('softmax'))

adam = Adam(lr=1e-4)

model.compile(optimizer=adam, loss='categorical_crossentropy', metrics=["accuracy"])


model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 125, 125, 32)      1568      
_________________________________________________________________
activation_11 (Activation)   (None, 125, 125, 32)      0         
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 62, 62, 32)        0         
_________________________________________________________________
activation_12 (Activation)   (None, 62, 62, 32)        0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 60, 60, 128)       36992     
_________________________________________________________________
activation_13 (Activation)   (None, 60, 60, 128)       0         
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 30, 30, 128)       0         
__________

In [30]:
# In[51]:


batch_size = 100
nb_epoch = 20
history = model.fit(data_train, label_train3, batch_size=batch_size, epochs=nb_epoch, verbose=1, validation_split=0.1)




Train on 1089 samples, validate on 121 samples
Epoch 1/20
1089/1089 [==============================] - 20s 19ms/step - loss: 2.1708 - acc: 0.2938 - val_loss: 1.9231 - val_acc: 0.5702
Epoch 2/20
1089/1089 [==============================] - 20s 18ms/step - loss: 1.6299 - acc: 0.5179 - val_loss: 1.4078 - val_acc: 0.5702
Epoch 3/20
1089/1089 [==============================] - 20s 19ms/step - loss: 1.1707 - acc: 0.6804 - val_loss: 1.0010 - val_acc: 0.7273
Epoch 4/20
1089/1089 [==============================] - 20s 19ms/step - loss: 0.8086 - acc: 0.7723 - val_loss: 0.6418 - val_acc: 0.8099
Epoch 5/20
1089/1089 [==============================] - 20s 18ms/step - loss: 0.6247 - acc: 0.8044 - val_loss: 0.5468 - val_acc: 0.8512
Epoch 6/20
1089/1089 [==============================] - 21s 19ms/step - loss: 0.4904 - acc: 0.8558 - val_loss: 0.4662 - val_acc: 0.8512
Epoch 7/20
1089/1089 [==============================] - 21s 19ms/step - loss: 0.3834 - acc: 0.8916 - val_loss: 0.4999 - val_acc: 0.8182
E

In [31]:
model.save('model.h5')

In [37]:
label = list(set(label_test))
label
label_test2 = []

for i in label_test:
    label_test2.append(label.index(i))

label_test3 = np_utils.to_categorical(label_test2 , 12)
print(label_test3)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [41]:

loss, acc = model.evaluate(data_test, label_test3, verbose=0)
print("loss",loss)
print("acc",acc)

loss 1.2163160737596725
acc 0.8439306358381503


In [ ]:
# In[41]:
data_test[0][0]

In [ ]:
# In[5]:
model = load_model('model.h5')

In [ ]:
# In[56]:
history.history
# In[6]:
print(model.summary())
# In[7]:
plot_model(model, to_file='model_plot.png', show_shapes=True, show_layer_names=True)
